FACEBOOK_APP_ID = ENV['FACEBOOK_APP_ID']
FACEBOOK_APP_SECRET = ENV['FACEBOOK_APP_SECRET']
GOOGLE_MAPS_API_KEY = ENV["GOOGLE_MAPS_API_KEY"]
S3_REGION = ENV["S3_REGION"]
S3_HOST_NAME = ENV["FACEBOOK_APP_SECRET"]
BUCKET = ENV["BUCKET"]
S3_ACCESS_KEY_ID = ENV["S3_ACCESS_KEY_ID"]
S3_SECRET_ACCESS_KEY = ENV["S3_SECRET_ACCESS_KEY"]

