# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



Country.create(name: "Afghanistan", capital: "Kabul", currency: "Afghani", population: '33 million', language: 'Pashto/Dari', visa: 'https://www.afghanembassy.us/consulate/visa/')
Country.create(name: "Albania", capital: "Tirana", currency: "Lek", population: '3.5 million', language: 'Albanian', visa: 'http://www.ambasadat.gov.al/japan/sites/default/files/Who_can_enter_Albania_without_a_Visa-word_0.pdf')
Country.create(name: "Algeria", capital: "Kabul", currency: "Dinar", population: '40 million', language: 'Arabic', visa: 'http://www.algerianembassy.org/consular-affairs/visa-instructions.html')
Country.create(name: "Andorra", capital: "Andorra La Vella", currency: "Euro", population: '85,000', language: 'Catalan', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Angola", capital: "Luanda", currency: "Kwanza", population: '25 million', language: 'Portuguese', visa: 'http://www.angola.org/index.php?page=english')
Country.create(name: "Antarctica", capital: "N/A", currency: "None", population: '5,000', language: 'N/A', visa: 'A passport is required for travel through the country or countries that you transit through en route to and from Antarctica.')
Country.create(name: "Antigua and Barbuda", capital: "St. John", currency: "", population: '91000', language: 'English', visa: 'http://www.antigua-barbuda.org/Agtip01a.htm')
Country.create(name: "Argentina", capital: "Buenes Aires", currency: "Argentinian Peso", population: '42 million', language: 'Spanish', visa: 'http://www.migraciones.gov.ar/accesible/indexN.php?visas')
Country.create(name: "Armenia", capital: "Yerevan", currency: "Dram", population: '3 million', language: 'Armenian', visa: 'http://mfa.am/en/visa/')
Country.create(name: "Australia", capital: "Sydney", currency: "Australian Dollar", population: '23 million', language: 'English', visa: 'http://www.australia.gov.au/help-and-contact/faqs/visas-and-immigration')
Country.create(name: "Austria", capital: "Vienna", currency: "Euro", population: '8.5 million', language: 'German', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Azerbaijan", capital: "Baku", currency: "Manat", population: '10 million', language: 'Azerbaijani', visa: 'http://mfa.gov.az/en/content/749')
Country.create(name: "Bahamas", capital: "Nassau", currency: "Bahamian Dollar", population: '400,000', language: 'English', visa: 'http://www.bahamas.gov.bs/wps/portal/public/Visiting/Visa%20Requirements/!ut/p/b1/vZTJjqMwGISfpR8gjc3OkS2EYCDsywU5CUsWAgmQAE8_iaalllqansv02CdLVf-nKuk3kRIJ5Hmeg4AHFBET6QXfDyXuD80Fn1_vlM0ozTYdmeZNnqUFoEPf0hV1Q2k--xQkTwH4wxHBbz_QTFF8-jUkMk-_zSDKWELHg0RExKtkluROf6iqm43BYCeu2eG46cqWUXlZBktQ-xbmnF7BN4rMTJxvrZJWXbcVaMbbmU4L7mPWV14yrStseBEwht2UBbg4RZfrwAUerpdaPw_TsNhwfkWRUdWspgHVSPSVZchXbsnqU54ZHhwRFXZDDU5FWkXCuWEfI7sF6JYgfM_K4txGEvrI_E2ov3QWEen3tZAfgm9qtVZNnRPJU8Z9zuHZ9Qtl2AYSDGplkoRPxIDOvOPU6vNpdo-cA0wwGv5RB1AFsD8qgbVVgWXZ0EPmA87B2Ksl8AC0rVM3-oK_2YduIIkiR--p8ivQJv0XUIasETDAI7mfBn5NSP1noEr_eKUGST2BiEIWL0PgcP8ZyP77hGsiPWzr98eufgfvAsc-fxog8AyAJENxRHhMWEF57b9uFVUeavkxn8Pg8CjXYhLYtQyqddNuJjde3yehcUrpmNQFl6y0seMVflxIjhcE1zZI2VuuYSXF0iAVKylujL58BPy9jNtLFN60vlNMUlR6hbmjRWsqVzxL3oEZla0LgwzXe3kXLr2eQ5MTudkpCVPljg5ZVcDc4wy9SM2quItdt7fwCNgbpZel3xWRXLHRZNGFtWczhxu5Kw7zTFQOm1t6eiPq9IymxalQ4vnzim9vvwCjAZGJ/dl4/d5/L2dBISEvZ0FBIS9nQSEh/')
Country.create(name: "Bahrain", capital: "Manama", currency: "Bahraini Dinar", population: '1.5 million', language: 'Arabic', visa: 'http://www.mofa.gov.bh/Default.aspx?tabid=147')
Country.create(name: "Bangladesh", capital: "Dhaka", currency: "Taka", population: '156 million', language: 'Bengali', visa: 'http://www.bangladeshconsulatela.com/visa.html')
Country.create(name: "Barbados", capital: "Bridgetown", currency: "Barbadian Dollar", population: '285,000', language: 'English', visa: 'http://www.foreign.gov.bb/UserFiles/File/June%202012.pdf')
Country.create(name: "Belarus", capital: "Minsk", currency: "Belarusian Ruble", population: '9.5 million', language: 'Belarusian/Russian', visa: 'http://mfa.gov.by/en/visa/ -- Belarus now offers 5 days visa free travel from select countries')
Country.create(name: "Belgium", capital: "Brussels", currency: "Euro", population: '23000', language: 'Dutch/French', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Belize", capital: "Belize City", currency: "Belize Dollar", population: '370,000', language: 'English', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_Belize')
Country.create(name: "Benin", capital: "Porto-Novo", currency: "West African Cfa/Franc", population: '11 million', language: 'French', visa: 'http://www.beninembassy.us/benin-consulate.html')
Country.create(name: "Bhutan", capital: "Thimphu", currency: "Bhutanese Ngultrum", population: '750,000', language: 'Dzongkha', visa: 'http://www.tourism.gov.bt/plan/visa')
Country.create(name: "Bolivia", capital: "La Paz", currency: "Boliviano", population: '10.5 million', language: 'Spanish', visa: 'http://www.boliviawdc.org/consulate/visas')
Country.create(name: "Bosnia & Herzegovina", capital: "Sarajevo", currency: "Mark", population: '4 million', language: 'Bosnian', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_Bosnia_and_Herzegovina')
Country.create(name: "Botswana", capital: "Gaborone", currency: "Pula", population: '2 million', language: 'Setswana/English', visa: 'http://www.gov.bw/en/Visitors/')
Country.create(name: "Brazil", capital: "Brasilia", currency: "Real", population: '200 million', language: 'Portuguese', visa: 'http://cgwashington.itamaraty.gov.br/en-us/visa_requirements_by_country.xml')
Country.create(name: "Brunei", capital: "Bandar Seri Begawan", currency: "Brunei Dollar", population: '410,000', language: 'Malay', visa: 'http://www.borneo.com.au/general/borneo-visas/brunei-visas')
Country.create(name: "Bulgaria", capital: "Sofia", currency: "Lev", population: '7 million', language: 'Bulgarian', visa: 'http://www.mfa.bg/en/pages/109/index.html')
Country.create(name: "Burkina Faso", capital: "Ouagadougou", currency: "West African Cfa", population: '17 million', language: 'French', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_Burkina_Faso')
Country.create(name: "Burundi", capital: "Bujumbura", currency: "Burundian Franc", population: '10 million', language: 'French/Kirundi', visa: 'http://www.burundiembassy-germany.de/index.php?en_visa')
Country.create(name: "Cambodia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Cameroon", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Canada", capital: "Ottawa", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Cape Verde", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Central African Republic", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Chad", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Chile", capital: "Santiago", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "China", capital: "Beijing", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Colombia")
Country.create(name: "Comoros", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Congo, Democratic Republic of", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Congo, Republic of", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Costa Rica", capital: "San Jose", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Croatia", capital: "Zagreb", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Cuba", capital: "Havana", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Cyprus", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Czech Republic", capital: "Prague", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Denmark", capital: "Copenhagen", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Dijbouti", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Dominica", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Dominican Republic", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Ecaudor", capital: "Quito", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Egypt", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "El Salvador", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Equatorial Guinea", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Eritrea", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Estonia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Ethopia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Fiji", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Finland", capital: "Helsinki", currency: "Euro", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "France", capital: "Paris", currency: "Euro", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "French Guinea", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Gabon", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Gambia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Georgia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Germany", capital: "Berlin", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Ghana", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Greece", capital: "Athens", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Grenda", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Guatemala", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Guinea", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Guinea-Bissau", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Guyana", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Haiti", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Honduras", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Hungary", capital: "Budapest", currency: "Forint", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Iceland", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "India", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Indonesia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Iran", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Iraq", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Ireland", capital: "Dublin", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Israel", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Italy", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Ivory Coast", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Jamaica", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Japan", capital: "Tokyo", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Jordan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Kazakhstan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Kenya", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Kiribati", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Kosovo", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Kuwait", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Kyrgyzstan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Laos", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Latvia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Lebanon", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Lesotho", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Liberia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Libya", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Liechtenstein", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Lithuania", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Luxembourg", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Macedonia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Madagascar", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Malawi", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Malaysia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Maldives", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Mali", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Malta", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Mauritania", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Mauritius", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Mexico", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Micronesia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Moldova", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Monaco", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Mongolia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Montenegro", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Morocco", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Mozambique", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Myanmar", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Namibia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Nepal", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Netherlands", capital: "Amsterdam", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "New Zealand", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Nicaragua", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Niger", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Nigeria", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "North Korea", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Norway", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Oman", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Pakistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Panama", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Papua New Guinea", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Paraguay", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Peru", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Philippines", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Poland", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Portugal", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Qatar", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Romania", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Russia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Rwanda", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Saint Kitts And Nevis", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Saint Lucia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Saint Vincent And Grenadines", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Samoa", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "San Marino", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Sao Tome And Principe", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Saudi Arabia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Senegal", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Serbia", capital: "Belgrade", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Seychelles", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Sierra Leone", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Singapore", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Slovakia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Slovenia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Solomon Islands", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Somalia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "South Africa", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Spain", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Sri Lanka", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Sudan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Suriname", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Swaziland", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Sweden", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Switzerland", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Syria", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Taiwan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Tajikistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Tanzania", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Thailand", capital: "Bangkok", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Timor-Leste", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Togo", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Tonga", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Trinidad & Tobogo", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Tunisia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Turkey", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Turkmenistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Uganda", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Ukraine", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "United Arab Emirates", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "United Kingdom", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "United States", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Uruguay", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Uzbekistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Vanuatu", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Vatican City", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Venezuela", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Vietnam", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Western Sahara", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Yemen", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Zambia", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Zimbabwe", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)     