# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



         
countrylist = ["Other Country Or Territory", "Argentina", "Armenia", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic", "Congo, Republic Of", "Costa Rica", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "England", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Finland", "France", "French Guiana", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria", "North Korea", "Norway", "Oman", "Pakistan", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Puerto Rico", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "Spain", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"]     

Country.create(name: "Afghanistan", capital: "Kabul", currency: "Afghani", population: '33 million', language: 'Pashto/Dari', visa: 'https://www.afghanembassy.us/consulate/visa/')
Country.create(name: "Albania", capital: "Tirana", currency: "Lek", population: '3.5 million', language: 'Albanian', visa: 'http://www.ambasadat.gov.al/japan/sites/default/files/Who_can_enter_Albania_without_a_Visa-word_0.pdf')
Country.create(name: "Algeria", capital: "Kabul", currency: "Dinar", population: '40 million', language: 'Arabic', visa: 'http://www.algerianembassy.org/consular-affairs/visa-instructions.html')
Country.create(name: "Andorra", capital: "Andorra La Vella", currency: "Euro", population: '85,000', language: 'Catalan', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Angola", capital: "Luanda", currency: "Kwanza", population: '25 million', language: 'Portuguese', visa: 'http://www.angola.org/index.php?page=english')
Country.create(name: "Antarctica", capital: "N/A", currency: "None", population: '5,000', language: 'N/A', visa: 'A passport is required for travel through the country or countries that you transit through en route to and from Antarctica.')
Country.create(name: "Antigua and Barbuda", capital: "St. John", currency: "", population: '91000', language: 'English', visa: 'http://www.antigua-barbuda.org/Agtip01a.htm')
Country.create(name: "Argentina", capital: "Buenes Aires", currency: "Argentinian Peso", population: '42 million', language: 'Spanish', visa: 'http://www.migraciones.gov.ar/accesible/indexN.php?visas')
Country.create(name: "Armenia", capital: "Yerevan", currency: "Dram", population: '3 million', language: 'Armenian', visa: 'http://mfa.am/en/visa/')
Country.create(name: "Australia", capital: "Sydney", currency: "Australian Dollar", population: '23 million', language: 'English', visa: 'http://www.australia.gov.au/help-and-contact/faqs/visas-and-immigration')
Country.create(name: "Austria", capital: "Vienna", currency: "Euro", population: '8.5 million', language: 'German', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Azerbaijan", capital: "Baku", currency: "Manat", population: '10 million', language: 'Azerbaijani', visa: 'http://mfa.gov.az/en/content/749')
Country.create(name: "Bahamas", capital: "Nassau", currency: "Bahamian Dollar", population: '400,000', language: 'English', visa: 'http://www.bahamas.gov.bs/wps/portal/public/Visiting/Visa%20Requirements/!ut/p/b1/vZTJjqMwGISfpR8gjc3OkS2EYCDsywU5CUsWAgmQAE8_iaalllqansv02CdLVf-nKuk3kRIJ5Hmeg4AHFBET6QXfDyXuD80Fn1_vlM0ozTYdmeZNnqUFoEPf0hV1Q2k--xQkTwH4wxHBbz_QTFF8-jUkMk-_zSDKWELHg0RExKtkluROf6iqm43BYCeu2eG46cqWUXlZBktQ-xbmnF7BN4rMTJxvrZJWXbcVaMbbmU4L7mPWV14yrStseBEwht2UBbg4RZfrwAUerpdaPw_TsNhwfkWRUdWspgHVSPSVZchXbsnqU54ZHhwRFXZDDU5FWkXCuWEfI7sF6JYgfM_K4txGEvrI_E2ov3QWEen3tZAfgm9qtVZNnRPJU8Z9zuHZ9Qtl2AYSDGplkoRPxIDOvOPU6vNpdo-cA0wwGv5RB1AFsD8qgbVVgWXZ0EPmA87B2Ksl8AC0rVM3-oK_2YduIIkiR--p8ivQJv0XUIasETDAI7mfBn5NSP1noEr_eKUGST2BiEIWL0PgcP8ZyP77hGsiPWzr98eufgfvAsc-fxog8AyAJENxRHhMWEF57b9uFVUeavkxn8Pg8CjXYhLYtQyqddNuJjde3yehcUrpmNQFl6y0seMVflxIjhcE1zZI2VuuYSXF0iAVKylujL58BPy9jNtLFN60vlNMUlR6hbmjRWsqVzxL3oEZla0LgwzXe3kXLr2eQ5MTudkpCVPljg5ZVcDc4wy9SM2quItdt7fwCNgbpZel3xWRXLHRZNGFtWczhxu5Kw7zTFQOm1t6eiPq9IymxalQ4vnzim9vvwCjAZGJ/dl4/d5/L2dBISEvZ0FBIS9nQSEh/')
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Afghanistan", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)