# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)



Country.create(name: "Afghanistan", capital: "Kabul", currency: "Afghani", population: '33 million', language: 'Pashto/Dari', visa: 'https://www.afghanembassy.us/consulate/visa/')
Country.create(name: "Albania", capital: "Tirana", currency: "Lek", population: '3.5 million', language: 'Albanian', visa: 'http://www.ambasadat.gov.al/japan/sites/default/files/Who_can_enter_Albania_without_a_Visa-word_0.pdf')
Country.create(name: "Algeria", capital: "Kabul", currency: "Dinar", population: '40 million', language: 'Arabic', visa: 'http://www.algerianembassy.org/consular-affairs/visa-instructions.html')
Country.create(name: "Andorra", capital: "Andorra La Vella", currency: "Euro", population: '85,000', language: 'Catalan', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Angola", capital: "Luanda", currency: "Kwanza", population: '25 million', language: 'Portuguese', visa: 'http://www.angola.org/index.php?page=english')
Country.create(name: "Antarctica", capital: "N/A", currency: "None", population: '5,000', language: 'N/A', visa: 'A passport is required for travel through the country or countries that you transit through en route to and from Antarctica.')
Country.create(name: "Antigua and Barbuda", capital: "St. John", currency: "", population: '91000', language: 'English', visa: 'http://www.antigua-barbuda.org/Agtip01a.htm')
Country.create(name: "Argentina", capital: "Buenes Aires", currency: "Argentinian Peso", population: '42 million', language: 'Spanish', visa: 'http://www.migraciones.gov.ar/accesible/indexN.php?visas')
Country.create(name: "Armenia", capital: "Yerevan", currency: "Dram", population: '3 million', language: 'Armenian', visa: 'http://mfa.am/en/visa/')
Country.create(name: "Australia", capital: "Sydney", currency: "Australian Dollar", population: '23 million', language: 'English', visa: 'http://www.australia.gov.au/help-and-contact/faqs/visas-and-immigration')
Country.create(name: "Austria", capital: "Vienna", currency: "Euro", population: '8.5 million', language: 'German', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Azerbaijan", capital: "Baku", currency: "Manat", population: '10 million', language: 'Azerbaijani', visa: 'http://mfa.gov.az/en/content/749')
Country.create(name: "Bahamas", capital: "Nassau", currency: "Bahamian Dollar", population: '400,000', language: 'English', visa: 'http://www.bahamas.gov.bs/wps/portal/public/Visiting/Visa%20Requirements/!ut/p/b1/vZTJjqMwGISfpR8gjc3OkS2EYCDsywU5CUsWAgmQAE8_iaalllqansv02CdLVf-nKuk3kRIJ5Hmeg4AHFBET6QXfDyXuD80Fn1_vlM0ozTYdmeZNnqUFoEPf0hV1Q2k--xQkTwH4wxHBbz_QTFF8-jUkMk-_zSDKWELHg0RExKtkluROf6iqm43BYCeu2eG46cqWUXlZBktQ-xbmnF7BN4rMTJxvrZJWXbcVaMbbmU4L7mPWV14yrStseBEwht2UBbg4RZfrwAUerpdaPw_TsNhwfkWRUdWspgHVSPSVZchXbsnqU54ZHhwRFXZDDU5FWkXCuWEfI7sF6JYgfM_K4txGEvrI_E2ov3QWEen3tZAfgm9qtVZNnRPJU8Z9zuHZ9Qtl2AYSDGplkoRPxIDOvOPU6vNpdo-cA0wwGv5RB1AFsD8qgbVVgWXZ0EPmA87B2Ksl8AC0rVM3-oK_2YduIIkiR--p8ivQJv0XUIasETDAI7mfBn5NSP1noEr_eKUGST2BiEIWL0PgcP8ZyP77hGsiPWzr98eufgfvAsc-fxog8AyAJENxRHhMWEF57b9uFVUeavkxn8Pg8CjXYhLYtQyqddNuJjde3yehcUrpmNQFl6y0seMVflxIjhcE1zZI2VuuYSXF0iAVKylujL58BPy9jNtLFN60vlNMUlR6hbmjRWsqVzxL3oEZla0LgwzXe3kXLr2eQ5MTudkpCVPljg5ZVcDc4wy9SM2quItdt7fwCNgbpZel3xWRXLHRZNGFtWczhxu5Kw7zTFQOm1t6eiPq9IymxalQ4vnzim9vvwCjAZGJ/dl4/d5/L2dBISEvZ0FBIS9nQSEh/')
Country.create(name: "Bahrain", capital: "Manama", currency: "Bahraini Dinar", population: '1.5 million', language: 'Arabic', visa: 'http://www.mofa.gov.bh/Default.aspx?tabid=147')
Country.create(name: "Bangladesh", capital: "Dhaka", currency: "Taka", population: '156 million', language: 'Bengali', visa: 'http://www.bangladeshconsulatela.com/visa.html')
Country.create(name: "Barbados", capital: "Bridgetown", currency: "Barbadian Dollar", population: '285,000', language: 'English', visa: 'http://www.foreign.gov.bb/UserFiles/File/June%202012.pdf')
Country.create(name: "Belarus", capital: "Minsk", currency: "Belarusian Ruble", population: '9.5 million', language: 'Belarusian/Russian', visa: 'http://mfa.gov.by/en/visa/ -- Belarus now offers 5 days visa free travel from select countries')
Country.create(name: "Belgium", capital: "Brussels", currency: "Euro", population: '23000', language: 'Dutch/French', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_the_Schengen_Area')
Country.create(name: "Belize", capital: "Belize City", currency: "Belize Dollar", population: '370,000', language: 'English', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_Belize')
Country.create(name: "Benin", capital: "Porto-Novo", currency: "West African Cfa/Franc", population: '11 million', language: 'French', visa: 'http://www.beninembassy.us/benin-consulate.html')
Country.create(name: "Bhutan", capital: "Thimphu", currency: "Bhutanese Ngultrum", population: '750,000', language: 'Dzongkha', visa: 'http://www.tourism.gov.bt/plan/visa')
Country.create(name: "Bolivia", capital: "La Paz", currency: "Boliviano", population: '10.5 million', language: 'Spanish', visa: 'http://www.boliviawdc.org/consulate/visas')
Country.create(name: "Bosnia & Herzegovina", capital: "Sarajevo", currency: "Mark", population: '4 million', language: 'Bosnian', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_Bosnia_and_Herzegovina')
Country.create(name: "Botswana", capital: "Gaborone", currency: "Pula", population: '2 million', language: 'Setswana/English', visa: 'http://www.gov.bw/en/Visitors/')
Country.create(name: "Brazil", capital: "Brasilia", currency: "Real", population: '200 million', language: 'Portuguese', visa: 'http://cgwashington.itamaraty.gov.br/en-us/visa_requirements_by_country.xml')
Country.create(name: "Brunei", capital: "Bandar Seri Begawan", currency: "Brunei Dollar", population: '410,000', language: 'Malay', visa: 'http://www.borneo.com.au/general/borneo-visas/brunei-visas')
Country.create(name: "Bulgaria", capital: "Sofia", currency: "Lev", population: '7 million', language: 'Bulgarian', visa: 'http://www.mfa.bg/en/pages/109/index.html')
Country.create(name: "Burkina Faso", capital: "Ouagadougou", currency: "West African Cfa", population: '17 million', language: 'French', visa: 'https://en.wikipedia.org/wiki/Visa_policy_of_Burkina_Faso')
Country.create(name: "Burundi", capital: "Bujumbura", currency: "Burundian Franc", population: '10 million', language: 'French/Kirundi', visa: 'http://www.burundiembassy-germany.de/index.php?en_visa')
Country.create(name: "Cambodia", capital: "Phnom Penh", currency: "Cambodian Riel", population: '15.2 million', language: 'Khmer', visa: 'https://www.evisa.gov.kh/')
Country.create(name: "Cameroon", capital: "Yaounde", currency: "Central African CFA Franc", population: '22.5 million', language: 'French/English', visa: false)
Country.create(name: "Canada", capital: "Ottawa", currency: "Canadian Dollar", population: '35 million', language: 'English/French', visa: false)
Country.create(name: "Cape Verde", capital: "Praia", currency: "Escudo", population: '500,000', language: 'Portuguese/Kriolu', visa: false)
Country.create(name: "Central African Republic", capital: "Bangui", currency: "Central African CFA Franc", population: '4.8 million', language: 'French/Sango', visa: false)
Country.create(name: "Chad", capital: "Kabul", currency: "KAd", population: '23000', language: 'Arabic', visa: false)
Country.create(name: "Chile", capital: "N'Djamena", currency: "Central African CFA Franc", population: '12.8 million', language: 'French/Arabic', visa: false)
Country.create(name: "China", capital: "Beijing", currency: "Renminbi", population: '1.35billion', language: 'Mandarian/Cantonese', visa: false)
Country.create(name: "Colombia", capital: "Bogota", currency: "Colombian Peso", population: "49 million", language: "Spanish", visa: false)
Country.create(name: "Comoros", capital: "Moroni", currency: "Comorian Franc", population: '735,000', language: 'Comorian/French/Arabic', visa: false)
Country.create(name: "Congo, Democratic Republic of", capital: "Kinshasa", currency: "Congolese Franc", population: '81 million', language: 'French', visa: false)
Country.create(name: "Congo, Republic of", capital: "Brazzaville", currency: "Central African CFA Franc", population: '4.6 million', language: 'French', visa: false)
Country.create(name: "Costa Rica", capital: "San Jose", currency: "Colon", population: '4.6 million', language: 'Spanish', visa: false)
Country.create(name: "Croatia", capital: "Zagreb", currency: "Kuna", population: '4.2 million', language: 'Croatian', visa: false)
Country.create(name: "Cuba", capital: "Havana", currency: "Cuban Dollar", population: '11.2 million', language: 'Spanish', visa: false)
Country.create(name: "Cyprus", capital: "Nicosia", currency: "Euro", population: '1.1 million', language: 'Greek/Turkish', visa: false)
Country.create(name: "Czech Republic", capital: "Prague", currency: "Koruna", population: '10.5 million', language: 'Czech', visa: false)
Country.create(name: "Denmark", capital: "Copenhagen", currency: "Krone", population: '5.7 million', language: 'Danish', visa: false)
Country.create(name: "Dijbouti", capital: "Dijbouti City", currency: "Dijboutian Franc", population: '850,000', language: 'French/Arabic', visa: false)
Country.create(name: "Dominica", capital: "Roseau", currency: "East Caribbean Dollar", population: '75,000', language: 'English', visa: false)
Country.create(name: "Dominican Republic", capital: "Santo Domingo", currency: "Dominican Peso", population: '10.5 million', language: 'Spanish', visa: false)
Country.create(name: "Ecaudor", capital: "Quito", currency: "US Dollar", population: '16.1 million', language: 'Spanish', visa: false)
Country.create(name: "Egypt", capital: "Cairo", currency: "Egyptian Pound", population: '92 million', language: 'Arabic', visa: false)
Country.create(name: "El Salvador", capital: "San Salvador", currency: "US Dollar", population: '6.5 million', language: 'Spanish', visa: false)
Country.create(name: "Equatorial Guinea", capital: "Malabo", currency: "Central African CFA Franc", population: '1.3 million', language: 'Spanish', visa: false)
Country.create(name: "Eritrea", capital: "Asmara", currency: "Nakfa", population: '6.3 million', language: 'No Official Language', visa: false)
Country.create(name: "Estonia", capital: "Talinn", currency: "Euro", population: '1.2 million', language: 'Estonian', visa: false)
Country.create(name: "Ethopia", capital: "Addis Ababa", currency: "Birr", population: '94 million', language: 'Arabic', visa: false)
Country.create(name: "Fiji", capital: "Suva", currency: "Fijian Dollar", population: '910,000', language: 'English/Fijian', visa: false)
Country.create(name: "Finland", capital: "Helsinki", currency: "Euro", population: '5.5 million', language: 'Finnish', visa: false)
Country.create(name: "France", capital: "Paris", currency: "Euro", population: '66 million', language: 'French', visa: false)
Country.create(name: "Gabon", capital: "Libreville", currency: "French", population: '1.5 million', language: 'French', visa: false)
Country.create(name: "Gambia", capital: "Banjui", currency: "Dalasi", population: '1.9 million', language: 'English', visa: false)
Country.create(name: "Georgia", capital: "Tbilisi", currency: "Lari", population: '4.5 million', language: 'Georgian', visa: false)
Country.create(name: "Germany", capital: "Berlin", currency: "Euro", population: '82 million', language: 'German', visa: false)
Country.create(name: "Ghana", capital: "Accra", currency: 'Cedi', population: '28 million', language: 'English', visa: false)
Country.create(name: "Greece", capital: "Athens", currency: "Euro", population: '11 million', language: 'Greek', visa: false)
Country.create(name: "Grenada", capital: "St. George's", currency: "East Caribbean Dollar", population: '110,000', language: 'English', visa: false)
Country.create(name: "Guatemala", capital: "Guatemala City", currency: "Queztal", population: '16.2 million', language: 'Spanish', visa: false)
Country.create(name: "Guinea", capital: "Conarky", currency: "Guinean Franc", population: '8.8 million', language: 'French', visa: false)
Country.create(name: "Guinea-Bissau", capital: "Bissau", currency: "West African CFA Franc", population: '1.6 million', language: 'Portuguese', visa: false)
Country.create(name: "Guyana", capital: "Georgetown", currency: "Guyanaese Dollar", population: '735,000', language: 'English', visa: false)
Country.create(name: "Haiti", capital: "Port-Au-Prince", currency: "Gourde", population: '10.3 million', language: 'French/Haitian Creole', visa: false)
Country.create(name: "Honduras", capital: "Tegucigalpa", currency: "Lempira", population: '8.2 million', language: 'Spanish', visa: false)
Country.create(name: "Hungary", capital: "Budapest", currency: "Forint", population: '9.8 million', language: 'Hungarian', visa: false)
Country.create(name: "Iceland", capital: "Reykjavik", currency: "Icelandic Krona", population: '335,000', language: 'Icelandic', visa: false)
Country.create(name: "India", capital: "New Delhi", currency: "Indian Rupee", population: '1.31 billion', language: 'Hindi/English', visa: false)
Country.create(name: "Indonesia", capital: "Jakarta", currency: "Rupiah", population: '255 million', language: 'Indonesian', visa: false)
Country.create(name: "Iran", capital: "Tehran", currency: "Rial", population: '82 million', language: 'Rial', visa: false)
Country.create(name: "Iraq", capital: "Bahgdad", currency: "Iraqi Dinar", population: '38 million', language: 'Arabic/Kurdish', visa: false)
Country.create(name: "Ireland", capital: "Dublin", currency: "Euro", population: '4.8 million', language: 'English/Irish', visa: false)
Country.create(name: "Israel", capital: "Jerusalem", currency: "Shekel", population: '8.4 million', language: 'Hebrew/Arabic', visa: false)
Country.create(name: "Italy", capital: "Rome", currency: "Euro", population: '61 million', language: 'Italian', visa: false)
Country.create(name: "Ivory Coast", capital: "Abidjan", currency: "West African CFA Franc", population: '24 million', language: 'French', visa: false)
Country.create(name: "Jamaica", capital: "Kingston", currency: "Jamaican dollar", population: '3.0 million', language: 'English', visa: false)
Country.create(name: "Japan", capital: "Tokyo", currency: "Yen", population: '126 million', language: 'Japanese', visa: false)
Country.create(name: "Jordan", capital: "Amman", currency: "Dinar", population: '9.8 million', language: 'Arabic', visa: false)
Country.create(name: "Kazakhstan", capital: "Astana", currency: "Tenge", population: '18 million', language: 'Kazahk', visa: false)
Country.create(name: "Kenya", capital: "Nairobi", currency: "Kenya Schilling", population: '46.5 million', language: 'English/Kishwali', visa: false)
Country.create(name: "Kiribati", capital: "Tarawa", currency: "Kiribati Or Australian Dollar", population: '103,000', language: 'English/Gilbertese', visa: false)
Country.create(name: "Kosovo", capital: "Pristina", currency: "Euro", population: '1.86 Million', language: 'Albanian/Serbian', visa: false)
Country.create(name: "Kuwait", capital: "Kuwait City", currency: "Kuwaiti Dinar", population: '4.4 million', language: 'Arabic', visa: false)
Country.create(name: "Kyrgyzstan", capital: "Bishkek", currency: "Som", population: '6 million', language: 'Kyrgyz/Russian', visa: false)
Country.create(name: "Laos", capital: "Vientiane", currency: "Kip", population: '7 million', language: 'Lao', visa: false)
Country.create(name: "Latvia", capital: "Riga", currency: "Euro", population: '2 million', language: 'Lativan', visa: false)
Country.create(name: "Lebanon", capital: "Beirut", currency: "Lebanese Pound", population: '6.2 million', language: 'Arabic', visa: false)
Country.create(name: "Lesotho", capital: "Maseru", currency: "Loti", population: '2.1 million', language: 'Sesotho/English', visa: false)
Country.create(name: "Liberia", capital: "Monrovia", currency: "Liberian Dollar", population: '4.5 million', language: 'English', visa: false)
Country.create(name: "Libya", capital: "Tripoli", currency: "Libyian Dinar", population: '6.5 million', language: 'Arabic', visa: false)
Country.create(name: "Liechtenstein", capital: "Vaduz", currency: "Swiss Franc", population: '37,000', language: 'German', visa: false)
Country.create(name: "Lithuania", capital: "Vilnius", currency: "Euro", population: '2.9 million', language: 'Lithuanian', visa: false)
Country.create(name: "Luxembourg", capital: "Luxembourg City", currency: "Euro", population: '600,000', language: 'French/German/Luxembourgish', visa: false)
Country.create(name: "Macedonia", capital: "Skopje", currency: "Macedonian Denar", population: '2.1 million', language: 'Macedonian', visa: false)
Country.create(name: "Madagascar", capital: "Antananarivo", currency: "Malagasy Ariary", population: '22.5 million', language: 'French/Malagasy', visa: false)
Country.create(name: "Malawi", capital: "Lilongwe", currency: "Kawacha", population: '6.4 million', language: 'English/Chichewa', visa: false)
Country.create(name: "Malaysia", capital: "Kuala Lumpor", currency: "Ringgit", population: '31.5 million', language: 'Malay', visa: false)
Country.create(name: "Maldives", capital: "Male", currency: "Maldives Time", population: '400,000', language: 'Maldivian', visa: false)
Country.create(name: "Mali", capital: "Bamako", currency: "West African CFA Franc", population: '15 million', language: 'French', visa: false)
Country.create(name: "Malta", capital: "Kabul", currency: "KAd", population: '23000', language: 'Italain', visa: false)
Country.create(name: "Mauritania", capital: "Nouakchott", currency: "Ouguiya", population: '4.1 million', language: 'Arabic', visa: false)
Country.create(name: "Mauritius", capital: "Port Louis", currency: "Mauritian rupee", population: '1.35 million', language: 'English/French/Creole', visa: false)
Country.create(name: "Mexico", capital: "Mexico City", currency: "Mexican Peso", population: '120 million', language: 'Spanish', visa: false)
Country.create(name: "Micronesia", capital: "Palikir", currency: "US Dollar", population: '100,000', language: 'English', visa: false)
Country.create(name: "Moldova", capital: "Chisineau", currency: "Leu", population: '3 million', language: 'Romanian', visa: false)
Country.create(name: "Monaco", capital: "Monaco", currency: "Euro", population: '38,000', language: 'French', visa: false)
Country.create(name: "Mongolia", capital: "Ulaanbaatar", currency: "Tögrög", population: '3 million', language: 'Mongolian', visa: false)
Country.create(name: "Montenegro", capital: "Podgorica", currency: "Euro", population: '620,000', language: 'Montenegrin', visa: false)
Country.create(name: "Morocco", capital: "Rabat", currency: "Moroccan dirham", population: '34 million', language: 'Arabic/Berber', visa: false)
Country.create(name: "Mozambique", capital: "Maputo", currency: "Mozambican Metical", population: '25 million', language: 'Portuguese', visa: false)
Country.create(name: "Myanmar", capital: "Naypyidaw", currency: "Kyat", population: '52 million', language: 'Burmese', visa: false)
Country.create(name: "Namibia", capital: "Windhoek", currency: "Namibian Dollar", population: '2.1 million', language: '9 Languages', visa: false)
Country.create(name: "Nepal", capital: "Kathmandu", currency: "Nepalese Rupee", population: '26.5 million', language: 'Nepali', visa: false)
Country.create(name: "Netherlands", capital: "Amsterdam", currency: "Euro", population: '17 million', language: 'Dutch', visa: false)
Country.create(name: "New Zealand", capital: "Wellington", currency: "New Zealand Dollar", population: '5 million', language: 'English', visa: false)
Country.create(name: "Nicaragua", capital: "Managua", currency: "Cordoba", population: '6.1 million', language: 'Spanish', visa: false)
Country.create(name: "Niger", capital: "Niamey", currency: "West African CFA", population: '18.5 million', language: 'French', visa: false)
Country.create(name: "Nigeria", capital: "Abuja", currency: "Naira", population: '188 million', language: 'English', visa: false)
Country.create(name: "North Korea", capital: "Pyounyang", currency: "Korean", population: '25 million', language: 'Korean', visa: false)
Country.create(name: "Norway", capital: "Oslo", currency: "Krone", population: '5.5 million', language: 'Norweigan', visa: false)
Country.create(name: "Oman", capital: "Muscat", currency: "Rial", population: '4.5 million', language: 'Arabic', visa: false)
Country.create(name: "Other")
Country.create(name: "Pakistan", capital: "Islamabad", currency: "Pakistani Rupee", population: '201 million', language: 'Erdu/English', visa: false)
Country.create(name: "Panama", capital: "Panama City", currency: "US Dollar", population: '4.1 million', language: 'Spanish', visa: false)
Country.create(name: "Papua New Guinea", capital: "Port Moresby", currency: "Papua New Guinean", population: '7 million', language: '5 Languages', visa: false)
Country.create(name: "Paraguay", capital: "Asuncion", currency: "Guaraní", population: '7 million', language: 'Spanish/Guaraní', visa: false)
Country.create(name: "Peru", capital: "Lima", currency: "Sol", population: '31 million', language: 'Spanish', visa: false)
Country.create(name: "Philippines", capital: "Manila", currency: "Peso", population: '100 million', language: 'Tagalog', visa: false)
Country.create(name: "Poland", capital: "Warsaw", currency: "Zloty", population: '38 Million', language: 'Polish', visa: false)
Country.create(name: "Portugal", capital: "Lisbon", currency: "Euro", population: '10.5 million', language: 'Portuguese', visa: false)
Country.create(name: "Qatar", capital: "Doha", currency: "Riyal", population: '2.5 million', language: 'Arabic', visa: false)
Country.create(name: "Romania", capital: "Bucharest", currency: "Leu", population: '19.5 million', language: 'Romanian', visa: false)
Country.create(name: "Russia", capital: "Moscow", currency: "Ruble", population: '145 million', language: 'Russian', visa: false)
Country.create(name: "Rwanda", capital: "Kigali", currency: "Rwandian Franc", population: '11 million', language: '4 Languages', visa: false)
Country.create(name: "Saint Kitts And Nevis", capital: "Basseterre", currency: "East Carribean Dollar", population: '54,961', language: 'English', visa: false)
Country.create(name: "Saint Lucia", capital: "Castries", currency: "East Carribean Dollar", population: '185,000', language: 'Creole Frence', visa: false)
Country.create(name: "Saint Vincent And Grenadines", capital: "Kingstown", currency: "East Carribean Dollar", population: '103,000', language: 'English', visa: false)
Country.create(name: "Samoa", capital: "Apia", currency: "Taia", population: '192,000', language: 'Samoan/English', visa: false)
Country.create(name: "San Marino", capital: "San Marino", currency: "Euro", population: '33,000', language: 'Italian', visa: false)
Country.create(name: "Sao Tome And Principe", capital: "Sao Tome", currency: "Dobra", population: '190,000', language: 'Portuguese', visa: false)
Country.create(name: "Saudi Arabia", capital: "Riyadh", currency: "Riyal", population: '33 Milion', language: 'Arabic', visa: false)
Country.create(name: "Senegal", capital: "Dakar", currency: "CFA Franc", population: '14.1 million', language: 'French', visa: false)
Country.create(name: "Serbia", capital: "Belgrade", currency: "Serbian Dinar", population: '7 million', language: 'Serbian', visa: false)
Country.create(name: "Seychelles", capital: "Victoria", currency: "Seychelles Rupee", population: '92,000', language: 'English/French/Creole', visa: false)
Country.create(name: "Sierra Leone", capital: "Freetown", currency: "Leone", population: '7 million', language: 'English/Bangla', visa: false)
Country.create(name: "Singapore", capital: "Singapore", currency: "Singapore Dollar", population: '5.6 million', language: '4 Languages', visa: false)
Country.create(name: "Slovakia", capital: "Bratislava", currency: "Euro", population: '5.5 million', language: 'Slovak', visa: false)
Country.create(name: "Slovenia", capital: "Ljubilana", currency: "Euro", population: '2 million', language: 'Slovene', visa: false)
Country.create(name: "Solomon Islands", capital: "Honiara", currency: "Solomon Islands Dollar", population: '640,000', language: 'English', visa: false)
Country.create(name: "Somalia", capital: "Mogadishu", currency: "Somali Shilling", population: '12.5 million', language: 'Somali/Arabic', visa: false)
Country.create(name: "South Africa", capital: "Johannesburg", currency: "Rand", population: '53 million', language: '11 Offical Languages', visa: 'http://www.home-affairs.gov.za/index.php/countries-exempt-from-sa-visas')
Country.create(name: "South Korea", capital: "Seoul", currency: 'Won', population: '50 million', language: "Korean", visa: false)
Country.create(name: "Spain", capital: "Madrid", currency: "Euro", population: '46 million', language: 'Spanish', visa: false)
Country.create(name: "Sri Lanka", capital: "Sri Jayawardenepura Kotte", currency: "Sri Lankan Rupee", population: '20 million', language: 'Sinhalese/Tamil', visa: false)
Country.create(name: "Sudan", capital: "Khartoum", currency: "Sudanese Pound", population: '40 million', language: 'Arabic/English', visa: false)
Country.create(name: "Suriname", capital: "Surinamese Dollar", currency: "KAd", population: '573,000', language: 'Dutch', visa: false)
Country.create(name: "Swaziland", capital: "Mbabane", currency: "Rand", population: '1.1 million', language: 'Swazi/English', visa: false)
Country.create(name: "Sweden", capital: "Stockholm", currency: "Krona", population: '10 million', language: 'Swedish', visa: false)
Country.create(name: "Switzerland", capital: "Bern", currency: "Swiss Franc", population: '8.4 million', language: 'French/German/Italian', visa: false)
Country.create(name: "Syria", capital: "Damascus", currency: "Syrian Pound", population: '17 million', language: 'Arabic', visa: false)
Country.create(name: "Taiwan", capital: "Taipei", currency: "New Taiwan Dollar", population: '23 million', language: 'Mandarin', visa: false)
Country.create(name: "Tajikistan", capital: "Dushanbe", currency: "Somoni", population: '8.6 million', language: 'Tajik', visa: false)
Country.create(name: "Tanzania", capital: "Dodoma", currency: "Tanzanian Shilling", population: '52 million', language: 'Swahili', visa: false)
Country.create(name: "Thailand", capital: "Bangkok", currency: "Baht", population: '67 million', language: 'Thai', visa: false)
Country.create(name: "Timor-Leste", capital: "Dimi", currency: "US Dollar", population: '23000', language: 'Tetum/Portuguese', visa: false)
Country.create(name: "Togo", capital: "Lome", currency: "CFA Franc", population: '7.5 million', language: 'French', visa: false)
Country.create(name: "Tonga", capital: "Nukuʻalofa", currency: "Paʻanga", population: '103,000', language: 'Tongon/English', visa: false)
Country.create(name: "Trinidad & Tobogo", capital: "Port of Spain", currency: "Trinidad & Tobogo Dollar", population: '1.3 million', language: 'English', visa: false)
Country.create(name: "Tunisia", capital: "Tunis", currency: "Tunesian Dinar", population: '11 million', language: 'Arabic', visa: false)
Country.create(name: "Turkey", capital: "Ankara", currency: "Lira", population: '80 million', language: 'Turkish', visa: false)
Country.create(name: "Turkmenistan", capital: "Ashgabat", currency: "Turkman New Manet", population: '5.1 million', language: 'Turkman', visa: false)
Country.create(name: "Uganda", capital: "Kampala", currency: "Ugandian Shilling", population: '38 million', language: 'English', visa: false)
Country.create(name: "Ukraine", capital: "Kiev", currency: "Hryvnia", population: '42 million', language: 'Ukrainian', visa: false)
Country.create(name: "United Arab Emirates", capital: "Abu Dhabi", currency: "UAE Dirham", population: '5.7 million', language: 'Arabic', visa: false)
Country.create(name: "United Kingdom", capital: "London", currency: "Pound", population: '65 million', language: 'English', visa: false)
Country.create(name: "United States", capital: "Washington D.C.", currency: "US Dollar", population: '325 million', language: 'English', visa: false)
Country.create(name: "Uruguay", capital: "Montevideo", currency: "Uruguayian Peso", population: '3.5 million', language: 'Spanish', visa: false)
Country.create(name: "Uzbekistan", capital: "Tashkent", currency: "Som", population: '32 million', language: 'Uzbek', visa: false)
Country.create(name: "Vanuatu", capital: "Port Vila", currency: "Vanuatu Vali", population: '286,000', language: 'Bislama/French/English', visa: false)
Country.create(name: "Vatican City", capital: "Vatican City", currency: "Euro", population: '1,000', language: 'Italian', visa: false)
Country.create(name: "Venezuela", capital: "Caracas", currency: "Bolivar Fuerte", population: '32 million', language: 'Spanish', visa: false)
Country.create(name: "Vietnam", capital: "Hanoi", currency: "Dong", population: '92 million', language: 'Vietnamese', visa: false)
Country.create(name: "Yemen", capital: "Sana'a", currency: "Yemeni Rial", population: '24.5 million', language: 'Arabic', visa: false)
Country.create(name: "Zambia", capital: "Lusaka", currency: "Kwacha", population: '16 million', language: 'English', visa: false)
Country.create(name: "Zimbabwe", capital: "Harere", currency: "US Dollar", population: '13 million', language: '16 Languages', visa: false)          